spring:
  datasource:
    url: jdbc:mysql://localhost:3306/HappySharing?useSSL=false&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.jdbc.Driver
    username: happysharing
    password: Zkk!]Vr7\L`0'M+$

  jpa:
    hibernate:
      search:
        default:
          directory_provider: filesystem
          indexBase: indexpath
      ddl-auto: update

    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC

  servlet:
    multipart:
      max-file-size: 10MB

app:
  jwtSecret: sjchsdHsiuhc
  jwtExpirationInMs: 604800000
